# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('itemType', models.IntegerField()),
                ('sectionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_section', to='fruitinfo.Fruit')),
            ],
        ),
    ]
